# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Chris Glass
tagline:             ''
description:         'My personal blog'
url:                 https://www.chrisglass.me
baseurl:             ''
paginate:            5


# About/contact
author:
  name:              Chris Glass
  url:               https://www.chrisglass.me
  email:             glassc@gmail.com

exclude: [docker-compose.yml]

gems: [jekyll-paginate]
